### ISSUE TITLE
Undock ships automatically after timeout

### ISSUE THREAD

**Issue by shobhitagarwal1612** [Software-Incubator/DirectMe#18]

**Comment by apoorvaeternity** [comment]
@utkbansal @shobhitagarwal1612  Are we going to have a cron job for this? We can also undock the ship when one of the user comes online.

**Comment by utkbansal** [comment]
No cron jobs for this. We cannot have any kind of latency. We will have to refresh the status when a user tries to access his ships in any way.

**Comment by utkbansal** [comment]
Fixed in #86
