### ISSUE TITLE
Implement leaderboard feature

### ISSUE THREAD

**Issue by shobhitagarwal1612** [Software-Incubator/DirectMe#20]

**Comment by apoorvaeternity** [comment]
What will be the basis for leaderboard?

**Comment by utkbansal** [comment]
@apoorvaeternity @shobhitagarwal1612 We will have to figure out an algorithm for calculating net worth on which the leaderboard will be based. Thoughts?

**Comment by shobhitagarwal1612** [comment]
@utkbansal We can consider following parameters 
Current level
Value of ships owned 
Total gold owned

**Comment by utkbansal** [comment]
@shobhitagarwal1612 Levels have to be decided yet. Do we still have our calculations?

**Comment by apoorvaeternity** [comment]
When are we going to update the leaderboard.Like every hour?

**Comment by utkbansal** [comment]
We will have a cron job most probably.

**Comment by utkbansal** [comment]
No cron jobs, it will be dynamic!
