### ISSUE TITLE
Secret key should be an environment variable.

### ISSUE THREAD

**Issue by utkbansal** [Software-Incubator/DirectMe#39]

**Comment by utkbansal** [comment]
@shobhitagarwal1612 Should we use some package to manage our env variables? Their number is increasing quite fast. Have a look at this https://github.com/joke2k/django-environ

**Comment by shobhitagarwal1612** [comment]
@utkbansal Yeah, it would be good to add an extra level of security too.

**Comment by utkbansal** [comment]
@shobhitagarwal1612 Okay then, either you can take it up or get @apoorvaeternity  up to speed on this.
